"""empty message

Revision ID: 20e32d40f925
Revises: 
Create Date: 2022-01-26 13:25:48.745991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e32d40f925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_novidade', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('validade', sa.String(length=10), nullable=False),
    sa.Column('data_lancamento', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('validade', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('endereco', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cupom', sa.Integer(), nullable=False),
    sa.Column('valor_desconto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=False),
    sa.Column('preco_frete', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('cupons_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cupons_id'], ['cupons.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NovidadesCarrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_novidade', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('novidades_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['novidades_id'], ['novidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProdutosCarrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Integer(), nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('produtos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['produtos_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProdutosCarrinho')
    op.drop_table('NovidadesCarrinho')
    op.drop_table('carrinho')
    op.drop_table('cupons')
    op.drop_table('usuario')
    op.drop_table('produtos')
    op.drop_table('novidades')
    # ### end Alembic commands ###
